### ISSUE TITLE
Allow sort by number columns.

### ISSUE THREAD

**Issue by hackwaly** [jchamet/html-table-sort#1]
Good extension!

In my option, sort columns contain numbers by number order instead of string order should be most desired.
Such as "price", "size", "total"..., they may have units (can group by units first then sort).

**Comment by jchamet** [comment]
Yeah, I noticed a problem given a list of item1, item10 and item100, the order isn't necessarily correct. Do you have any ideas for a solution?

**Comment by hackwaly** [comment]
I'm sorry I had not noticed that. I can do a pull request.
