### ISSUE TITLE
gets rid of column span

### ISSUE THREAD

**Issue by fenollp** [jchamet/html-table-sort#12]
See this table: https://www.rottentomatoes.com/top/bestofrt/top_100_science_fiction__fantasy_movies/
As soon as one clicks the columns get tighter together (look at the "100%" row, it seems there's only 0px of surrounding margin left).

Anyways thanks for creating this extension! I've been needing it for a long while.
Also, what do you think about adding a CI for continuous delivery (and to ensure us that the package we get really comes from here) such as this script: https://github.com/sindresorhus/refined-github/blob/master/.travis.yml ?

**Comment by jchamet** [comment]
Glad you've found this tool helpful! Not sure about the formatting thing, will look into it when time permits.

For continuous delivery, could you create a merge request? If it's as simple as copy paste + some changes, I'd want you to get contributor credit. If there's something you need from my side for this, please let me know.
