### ISSUE TITLE
No source code license or not obvious

### ISSUE THREAD

**Issue by Iiridayn** [jchamet/html-table-sort#7]
At https://chrome.google.com/webstore/detail/html-table-auto-sort/bpgbkjehkeffmmjfmdlmjjlffgkdcljp the page claims that this extension is open source, and links to this repository to demonstrate this. The text there encourages forking/contributing - but under what license? MIT? GPL? CC0/WTFPL? You have no obligation to license the code - just publicly displaying it is great too, but if you want to grant rights beyond looking at it, you might want to consider one of the above licenses :).

**Comment by jchamet** [comment]
Thank you! You are entirely right, I will use the MIT license
