### ISSUE TITLE
unable to sort tables not using "th", like gerrit changeset tables

### ISSUE THREAD

**Issue by ssbarnea** [jchamet/html-table-sort#8]
![topic rhos-ci-test code engineering code review 2017-06-14 11-54-33](https://user-images.githubusercontent.com/102495/27128895-46cbf9bc-50f8-11e7-8c84-d9f850ff57a3.jpg)

Can we make it work in this case?

**Comment by a-raccoon** [comment]
I'm encountering this issue as well.  Tables are classically composed of "tr" and "td", I hadn't even heard of "th" before today, and apparently most of the Internet agrees.  I can't find a page that this extension works on.

http://www.firelookout.org/lo-newmexico.html

**Comment by ssbarnea** [comment]
@a-raccoon I have there are lots of people that should RTFD :D

`<th>` happens to be standard since HTML3 or earler if I am not mistaken. It is still inside HTML5 with no plans to be deprecated and is supported by all browsers, so so excuses other than ignorance for not using it.

**Comment by a-raccoon** [comment]
Regardless, this browser extension is only as good as it is capable of working on other people's webpages.  If it doesn't work on other people's webpages, then it is lacking in usefulness.  90% of the academic and government documentation Internet is still composed of HTML 1.0 standard, and always will be.

**Comment by TorkelV** [comment]
I opened a pull request to fix this, but doesn't look like there's a lot of activity here.. 
You could download the source of my PR and add it to chrome manually if you need this feature :) Hopefully it will be added to a new release though
#17

**Comment by jchamet** [comment]
@TorkelV thank you for contributing, PRs are always appreciated! I'll review in the morning. And then let's see what we can do about that new release haha
