### ISSUE TITLE
Negative numbers are sorted incorrectly

### ISSUE THREAD

**Issue by whiskeysierra** [jchamet/html-table-sort#9]
![screenshot from 2017-11-16 09-39-49](https://user-images.githubusercontent.com/429981/32881629-1bed15e4-cab2-11e7-87d6-eec2f1bfaedd.png)

**Comment by dlh3** [comment]
Oh hey, didn't see this issue.  PR #13 addresses this bug, handling both negatives and floating-point numbers.

**Comment by TorkelV** [comment]
Should this be closed or is it still an issue? Seeing as @dlh3 says it was fixed in #13.

**Comment by jchamet** [comment]
Hadn't noticed
